name: Build and Deploy CloudTopia Weather Simulator

on:
  push:
    branches:
      - main

env:
  RESOURCE_GROUP: your-resource-group-name
  LOCATION: your-region
  ACR_NAME: cloudtopiaacr
  STORAGE_NAME: cloudtopiastorage${{ github.run_id }}  # or generate dynamically as needed
  CONTAINER_NAME: weather-detector

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build Docker image
      run: |
        az acr login --name $ACR_NAME
        docker build -t $ACR_NAME.azurecr.io/weather-simulator:latest ./weather-simulator
        docker push $ACR_NAME.azurecr.io/weather-simulator:latest

    - name: Deploy Bicep Template
      run: |
        az deployment group create \
          --resource-group $RESOURCE_GROUP \
          --template-file ./infrastructure/main.bicep \
          --parameters storageName=$STORAGE_NAME \
                       acrName=$ACR_NAME \
                       containerImage=$ACR_NAME.azurecr.io/weather-simulator:latest
