name: Build Image and Deploy Infrastructure

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ACR_NAME: cloudtopiaacr
  IMAGE_NAME: weather-simulator
  RESOURCE_GROUP: CloudTopiaRG

jobs:
  build-and-push:
    name: Build & Push Docker Image to ACR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure ACR Login
        run: az acr login --name $ACR_NAME

      - name: Build and Push Docker Image
        run: |
          docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:latest ./weather-simulator
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:latest

  deploy-infra:
    name: Deploy Bicep Infrastructure
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Bicep CLI
        run: az bicep install

      - name: Deploy Bicep Template
        run: |
          az deployment group create \
            --resource-group $RESOURCE_GROUP \
            --template-file infrastructure/main.bicep \
            --parameters containerImage="$ACR_NAME.azurecr.io/$IMAGE_NAME:latest"
